### ISSUE TITLE
Wrong code example 

### ISSUE THREAD

**Issue by wellitongervickas** [learning-zone/javascript-interview-questions#14]
[Q. What is the precedence order between local and global variables?
](https://github.com/learning-zone/javascript-interview-questions#q-what-is-the-precedence-order-between-local-and-global-variables)

Current:
```
var msg = "Good morning";
function greeting() {
  msg = "Good Evening";
  console.log(msg);
}
greeting();
```

Maybe missed "var" in inner variable:
```
var msg = "Good morning";
function greeting() {
  var msg = "Good Evening";
  console.log(msg);
}
greeting();
```

**Comment by learning-zone** [comment]
This question is about, local variable takes precedence over a global variable with the same name.
Here, we are overwriting global variable with local one, which is declared on top. So, this is not an issue.
