### ISSUE TITLE
Wrong topic title

### ISSUE THREAD

**Issue by wellitongervickas** [learning-zone/javascript-interview-questions#15]
[Q. What are the conventions to be followed for the usage of swtich case?
](https://github.com/learning-zone/javascript-interview-questions#q-what-are-the-conventions-to-be-followed-for-the-usage-of-swtich-case)
maybe:
Q. What are the conventions to be followed for the usage of switch case?

**Comment by learning-zone** [comment]
Fixed Typo, Thanks.
