### ISSUE TITLE
issues in questions 8 & 297... and its answers

### ISSUE THREAD

**Issue by Adam-Books** [learning-zone/javascript-interview-questions#18]
# 8: What are global variables?
**Your answer is:**
Global variables are those that are available throughout the length of the code without any scope. The var keyword is used to declare a local variable but if you omit it then it will become a global variable

```javascript
msg = "Hello"  // var is missing, it becomes global variable
```

The problem with global variables is the conflict of variable names of local and global scope. It is also difficult to debug and test the code that relies on global variables.

-------------------------------------------------------

But I think that:

Global variables are those that are available throughout the length of the code without any scope. The var keyword is used to declare declares a function-scoped or globally-scoped variable but if you omit it then it will become a global variable only.

```javascript
msg = "Hello"  // var is missing, it becomes a global variable
```

**But var in the 'Block scope' is still a global variable:**

```javascript
var x = 1;

if (x === 1) {
  var x = 2;

  console.log(x);
  // expected output: 2
}

console.log(x);
// expected output: 2
```

<hr />

#  297: In JavaScript, What is the difference between var x = 1 and x = 1?

Your Answer is: 

‘var x = 1’ will create a variable within the current scope. Given this is declared in a function, x will not be available outside it unless explicitly returned.

‘x = 1’ will create a variable within the global scope. Thus, any other code can access and alter its value. It is generally a bad practice to use variables in a global scope.

------------------------------------------------

But... I think that this is a wrong answer, Because in [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var) : 

<h3>The var statement declares a function-scoped or globally-scoped variable, optionally initializing it to a value.</h3>

and

in strict mode: 'x = 1' is not allowed.

So I hope you correct it.

### Because JavaScript has 3 types of scope:
- Block scope
- Function scope
- Global scope

**Comment by learning-zone** [comment]
Any reference provided for above definition will be appreciated.

**Comment by Adam-Books** [comment]
[MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var)

**Comment by learning-zone** [comment]
If you can justify your statement with provided reference will be appreciated.

**Comment by Adam-Books** [comment]
# Q 297: In JavaScript, What is the difference between var x = 1 and x = 1?

# I suggest this answer:

### var x = 1:

- Allowed in 'strict mode'.
- The var statement declares a function-scoped or globally-scoped variable, optionally initializing it to a value.
- Variables declared using var inside a { } block can be accessed from outside the block.
- Variables defined using var inside a function are not accessible (visible) from outside the function.
- Duplicate variable declarations using var will not trigger an error, even in strict mode, and the variable will not lose its value unless another assignment is performed.

```javascript
var x = 1;

if (x === 1) {
  var x = 2;

  console.log(x);
  // expected output: 2
}

console.log(x);
// expected output: 2
```

```javascript
var x = 5; // global
function someThing(y) {
  var x = 3; // local
  var z = x + y;
  console.log(z);
}
someThing(4); // 7
console.log(x); // 5
```

### x = 1:
- Not allowed in 'strict mode'.
- Undeclared Variables like: x = 1 is accessible in: (Block scope - Function scope - Global scope)
- Outside of strict mode, however, if you assign a value to a name that has not been declared with let, const, or var, you’ll end up creating a new global variable. It will be global no matter how deeply nested within functions and blocks your code is, which is almost certainly not what you want, is bug-prone, and is one of the best reasons for using strict mode!
- Global variables created in this accidental way are like global variables declared with var: they define properties of the global object.
- Unlike the properties defined by proper var declarations, these properties can be deleted with the delete operator.
- Not recommended.

```javascript
var x = 5; // global
function someThing(y) {
  x = 1; // still global!
  var z = x + y;
  console.log(z);
}
someThing(4) // 5
console.log(x) // 1
```

# References:
 - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var
 - https://www.w3schools.com/js/js_scope.asp
 - [JavaScript: The Definitive Guide by David Flanagan, 7th Edition, O’Reilly, 2020.](https://ca1lib.org/book/5533416/34944c)

**Comment by learning-zone** [comment]
Please create a PR, so that repository can be updated.

**Comment by Adam-Books** [comment]
OK... happy new year ☺

**Comment by learning-zone** [comment]
Happy New Year 🎉 😄
