### ISSUE TITLE
Problems directory removed 

### ISSUE THREAD

**Issue by tasawar-hussain** [learning-zone/javascript-interview-questions#28]
https://github.com/learning-zone/javascript-interview-questions/commit/fd275d5255a64c1c4a711a5bfa1a5ff067da62cf#diff-5fbfdce5c2abc62be0d0053fc1639ecf9ed0ec06fafdd8cca32410f2c8f9d1ca

The problems folder was removed in this commit, was this intentional?

**Comment by learning-zone** [comment]
Hi @tasawar-hussain 

JavaScript problems is more related to code practice, so it is moved under below repository.

https://github.com/learning-zone/JavaScript-Coding-Practice
